# Generated by Django 4.1.5 on 2023-02-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Admin_incharge',
            new_name='admin_incharge',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='In_marketplace',
            new_name='in_marketplace',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Owned_by',
            new_name='owned_by',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Area_Code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='address',
            name='City',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Dimension',
        ),
        migrations.RemoveField(
            model_name='address',
            name='District',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Door_no',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Extend_of_land',
        ),
        migrations.RemoveField(
            model_name='address',
            name='House_no',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Metadata',
        ),
        migrations.RemoveField(
            model_name='address',
            name='State',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Street_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Sub_registrar_office',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Total_extend',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Village',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Ward_no',
        ),
        migrations.AddField(
            model_name='address',
            name='token_id',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='area_code',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='category',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='dimension',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='door_no',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='extend_of_land',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='house_no',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='metadata',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='street_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='sub_registrar_office',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='total_extend',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='village',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='address',
            name='ward_no',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
